config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #creates the route to 'pages/homepage' page
  #get 'pages/homepage', to: 'pages#homepage'
  root 'pages#homepage'
  #created the route to 'pages/about' page
  #get 'pages/about', to: 'pages#about'
  get 'about', to: 'pages#about'
  #Created all paths (add,delete, edit, show, update)
  resources :articles 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
#Ruby class that interacts with the article table 
class Article < ActiveRecord::Base
# Validates that data being saved to the database is valid and it doesn't just contain "nil"
	# validates that the data has a title and that it meets the length constraints: 
	validates :title, presence: true, length: {minimum: 3, maximum: 50}
	#validates that it has a description and that the length meets the certain constraints: 
	validates :description, presence:true, length: {minimum: 10, maximum: 300}

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# The four methods "edit, update, show, and destroy" will call the set_article method
	before_action :set_article, only: [:edit, :update, :show, :destroy]

	def index
		@articles = Article.all
	end
	def new 
		@article = Article.new
	end 

	def edit 
		# Finding the article:

	end


	def create 
		# Going to display the information 
		
		@article = Article.new(article_params)
		#Saving the article:		
		if @article.save
			# Going to display the information 
			flash[:notice] = "Article was successfully created!"
			redirect_to article_path(@article)
		else 
			render 'new'
		end 
	end 

	def update
		if @article.update(article_params) 
			flash[:notice] = "Article was successfully udpated!"
			redirect_to article_path(@article)
		else
			render 'edit'
		end 
	end

	def show 
	
	end 

	def destroy
		@article.destroy
		flash[:notice] = "Article was successfully deleted"
		redirect_to articles_path
	end 

	private 
		def set_article
			@article = Article.find(params[:id])
		end	

		def article_params
			params.require(:article).permit(:title, :description)
		end 
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	


	def homepage

	end 

	def about 

	end 

end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<!--********************Displaying errors**********************--> 
<% if @article.errors.any? %>
<h2>The following errors were caused by:</h2>
<ul>
<% @article.errors.full_messages.each do |message|%>
	<li><%= message %></li>
	 <%end%> 
</ul>
<%end%>
<!--********************************************************* -->

<div class='row'>
	<div class='col-xs-12'>


	<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |c| %>

		<div class="form-group">
			<div class="control-label col-sm-2">

				<%= c.label :title %>
			</div>
			<div class="col-sm-8">
				<%= c.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true%>
			</div>
		</div>

		<div class="form-group">
			<div class="control-label col-sm-2">
			<%= c.label :description %>
		</div>
		<div class="col-sm-8">
			<%= c.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
		</div>

		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
			<%= c.submit class: "btn btn-primary btn-lg"%>
		</div>
	</div>

	<%end%>
	<div class="col-xs-4 col-xs-offset-4">
		<!-- Adding link to be able to go back to the articles listing-->
		[ <%= link_to "Cancel request and Back to articles listing", articles_path %> ]
	</div>
	</div>
</div>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 style='color:red'>Listing all articles</h1>
<p>
<%= link_to "Create new article", new_article_path %>
</p>

<table>
	<!--Table Row-->
	<tr>
		<!--Table header -->
		<th>Title</th>
		<th>Description</th>
	</tr>
	<!-- Editing and iterating through all of the articles -->
	<tr>
		<% @articles.each do |article| %>
		<td>
			<%= article.title %>
		</td>
		<td>
			<%= article.description %>
		</td>
		<!-- Adding edit link to each article! -->
		<td>
			<%= link_to "Edit", edit_article_path(article) %>
		</td>
		<!-- Adding show link to each article!--> 
		<td>
			<%= link_to "Show", article_path(article) %>
		</td>
		<td>
			<%= link_to "Delete", article_path(article), method: :delete, data:{confirm: "Are you sure?"} %>
		</td>
	</tr>
	<% end %>

</table>

app/views/articles/new.html.erb
<h1 align ="center">Create an article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>
	Title: <%= @article.title %>
</p>
<p>
	Description: <%= @article.description %>
</p>

<!-- Adding link to be able to go back to the index page-->
<%= link_to "Back to articles listing", articles_path %>
<p>
<!-- Linking to being able to edit post as well --> 
<%= link_to  "Edit Posting", edit_article_path(@article)%>
</p>

app/views/layouts/_footer.html.erb
<div class ="container">
	<footer class="footer">
		<small>
			Copyright &copy; <p>Christian Lopez</p>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<%flash.each do |name, message|%>
  	<ul>
  		<li><%=message%></li>
  	</ul>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- Embedded Ruby -->  
      <%= link_to "Alpha-Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- Embeded Ruby -->
        <li><%= link_to "Articles", articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!-- Embeded Ruby --> 
            <li><%= link_to "New Article", new_article_path%></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!--This a wrapper file, so everything that is written here will be displayed on every page. The "Yield"lets you add the other content.-->
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Rendering to the navigation -->
    <%= render 'layouts/navigation' %>
  	<!-- Rendering to the _messages partial -->
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 align='center'>About</h1>

<p>Hello, my name is christian and this is my site; I hope you like it!</p>
<!--Linking to the home page-->
<%= link_to 'Home', root_path %> 

app/views/pages/homepage.html.erb
<div class="center jumbotron">	
	<h1>ALPHA BLOG</h1>

	<!-- Linking to the about page and the articles path -->
	<%= link_to "Sign up now","#" , class: "btn btn-danger btn-lg btn-xlarge" %>
	